version: "3"
services: 
    database-carconnect:
        image: mongo:4.2.5
        container_name: database-carconnect
        ports: 
            - "27017:27017"
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=admincarconnect
            - MONGO_INITDB_ROOT_PASSWORD=4Ehs2dK6M
            - MONGO_INITDB_DATABASE=api
        volumes: 
            - ./init-database.js:/docker-entrypoint-initdb.d/init-database.js:ro
            - database-carconnect:/data/db
        
    api-carconnect:
        container_name: api-carconnect
        links: 
            - database-carconnect
        ports: 
            - '3000:3000'
        build: .
volumes: 
    database-carconnect: